### PR TITLE
Fixing ResilientGetViewRenderer for Sitecore 8.1

### PR DESCRIPTION
**Pull request by mulate**
In Sitecore 8.1's Sitecore.Mvc.dll, the method GetAbsolutePath doesn't exist anymore. When running the site with the original dll, I'm getting the error "Method not found: 'System.String Sitecore.Mvc.Presentation.ViewRenderer.GetAbsoluteViewPath()'"

### CODE REVIEW

**Comment by kamsar** [comment]
I'd love to merge your PR but it seems to be misconfigured. It's set to merge my master branch into my isolationist branch (which was an old experiment).

For a PR to work, it needs to be from a branch on your forked repository into my master branch. At present your account doesn't seem to have any public repositories to merge from?

**Comment by kamsar** [comment]
I'm going to close this PR because once created, you can't edit the branches. I'm making Synthesis 8.1 compatible right now, so I'm going to fix this shortly.

**Comment by mulate** [comment]
Thanks for your time. Didn't know the process, so I'll do that next time :)

Since you're already working on compatibility, it's a win-win situation for me. :+1:

**Comment by kamsar** [comment]
:)

**Pull request closed without merging**
